security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: logout
                target: after_logout
            json_login:
                check_path: /login
            entry_point: App\Security\AuthenticationEntryPoint

    password_hashers:

        legacy:
            algorithm: bcrypt
            encode_as_base64: false
            iterations: 1

        App\Entity\User:
#            algorithm: bcrypt
            algorithm: argon
            migrate_from:
                - bcrypt # uses the "bcrypt" hasher with the default options

    enable_authenticator_manager: true
    erase_credentials: false