security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: logout
                target: after_logout
            json_login:
                check_path: /login
            entry_point: App\Security\AuthenticationEntryPoint

    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
